### ISSUE TITLE
The communication with Libsecret failed.

### ISSUE THREAD

**Issue by nxjosephofficial** [MikaelUrankar/flare-ports#1]
Hi, i got this error. I don't know how can i link my account. 
![2024-05-21-134615_1366x768_scrot](https://github.com/MikaelUrankar/flare-ports/assets/153529729/16d5e96a-7647-4b65-a372-10acfe72cf37)

**Comment by nxjosephofficial** [comment]
The only one that isn't installed was `libsecret` and i installed it but there is no change in the result.
```
DBus(
    Service(
        ZBus(
            MethodError(
                OwnedErrorName(
                    "org.freedesktop.DBus.Error.ServiceUnknown",
                ),
                Some(
                    "The name org.freedesktop.secrets was not provided by any .service files",
                ),
                Msg {
                    type: Error,
                    sender: UniqueName(
                        "org.freedesktop.DBus",
                    ),
                    reply-serial: 2,
                    body: Signature(
                        "s",
                    ),
                    fds: [],
                },
            ),
        ),
    ),
)
```

**Comment by MikaelUrankar** [comment]
org.freedesktop.secrets.service is provided by security/gnome-keyring, can you try to install this port?

**Comment by nxjosephofficial** [comment]
I installed it and now it ran without the issue. I linked my account successfully. Thanks for help. Maybe you would want to add it as a dependency.

**Comment by nxjosephofficial** [comment]
If I enable dbus system-wide in `/etc/rc.conf`, i get the following error.

![2024-05-23-194333_1366x768_scrot](https://github.com/MikaelUrankar/flare-ports/assets/153529729/175112f9-317c-41e7-816d-3b4a30b5e7d3)

**Comment by MikaelUrankar** [comment]
Try to run it under truss to find the file missing.

**Comment by MikaelUrankar** [comment]
Is it still an issue?

**Comment by nxjosephofficial** [comment]
Sorry for late reply.

Yes, it does still happen if `dbus` service is enabled in `/etc/rc.conf`.

**Comment by nxjosephofficial** [comment]
Here is the truss output of flare. [flare.log](https://github.com/user-attachments/files/16531088/flare.log)

There are too many "No such file or directory" entries.

I can discuss why it's not even launching while dbus is enabled system-wide on upstream issues.

**Comment by nxjosephofficial** [comment]
https://gitlab.com/schmiddi-on-mobile/flare/-/issues/217#note_2035737963

I can confirm that there are no issues if DBus service is enabled in the system and the DE is ran with DBus.

```
yusuf@hale ~ % grep dbus /etc/rc.conf
dbus_enable="YES"
yusuf@hale ~ % grep dbus .xinitrc
exec dbus-launch --exit-with-session --sh-syntax dwm
yusuf@hale ~ %
```
